title: "Wonchan Choi"
logo: /assets/img/logo.png
description: >
  Associate Professor @ UWM iSchool  
  <br>  
  Information Scientist
show_downloads: true
google_analytics: ""  # leave empty but valid
theme: jekyll-theme-minimal
