title: "Wonchan Choi"
logo: /assets/img/wchoi-pic-cropped.jpg
description: >
  Researcher in Library and Information Science
  <br>  
  Email: wchoi@uwm.edu
  [Google Scholar](https://scholar.google.com/citations?user=p5_1GbgAAAAJ&hl=en)  
  [ORCID]()
show_downloads: false
google_analytics: ""  # leave empty but valid
theme: jekyll-theme-minimal
